### ISSUE TITLE
Question on units for media fluxes

### ISSUE THREAD

**Issue by krcurtis** [resendislab/micom#5]
In the documentation when running minimal_medium(), what are the units for the fluxes returned? I'm guessing something like mMol / hr. Also when returning fluxes for a community, I noticed that the fluxes are broken down by metabolite and bacteria. Do the fluxes already include a scaling factor for the abundance of the bacteria in the community?

Thanks!

**Comment by cdiener** [comment]
The basic mass unit is the one used by your input models. For instance if you use AGORA its mmol. Exchange fluxes for the external medium (for instance the gut) and growth rates are in `mmol/h` as you state. So you have to divide those by the overall biomass in the gut or assume a total biomass of 1gDW. Internal fluxes for the bacteria are always renormalized to 1gDW so their unit is `mmol/(gDW*h)`. This is done to make fluxes comparable across bacteria.

Internally, micom connects compartments (external medium and bacteria) by scaling with abundances as you have correctly stated as described in https://resendislab.github.io/micom/logic.html#Exchanges-and-community-growth-rate.
